export const GAME_CONFIG = {
    // COIN_BONUS_SCORE : 100,
    // TILE_PERFECT_SCORE : 3,
    CORRECT_ANSWER_POINT : 10,
    DESIGN_SCREEN_WIDTH : 1280,
    DESIGN_SCREEN_HEIGHT : 720,
    GAME_DURATION_TIME : 30000, // for a match in milisecond
    HALF_DESIGN_SCREEN_WIDTH: 1280/2,
    HALF_DESIGN_SCREEN_HEIGHT: 720/2,
    MAP_WIDTH: 2250,
    MAP_HEIGHT: 1380,
    MIN_DISTANCE_ALLOW: 500,
}